### ISSUE TITLE
Creating Policy Rule Without Name Makes Object Directly Uneditable in UI

### ISSUE THREAD

**Issue by jdrew82** [nautobot/nautobot-app-firewall-models#233]
### Environment
* Python version: 3.10
* Nautobot version: 2.1.5
* nautobot-firewall-models version:  2.0.3

### Expected Behavior
Selecting individual check box next to Policy Rule without name and hitting Edit would take me to that specific object edit.

### Observed Behavior
Attempting to edit Policy Rule without name only allows for bulk edit as it appears the link to individual object is linked from the name.

### Steps to Reproduce
1. Setup Nautobot and Firewall Models App.
2. Create Address object and Policy Rule using object but don't include name on rule. 
3. Also create Policy Rule with a name.
4. View Policy Rule list and see how link to edit Policy Rule is on name and attempts to edit the rule without name goes to bulk edit view.

**Comment by bryanculver** [comment]
This is even more awkward in the Policy form as the name is missing as well: 
<img width="578" alt="image" src="https://github.com/user-attachments/assets/ed4f60fb-1ce0-4094-986d-f2c9786cea7d">


Name should be required looking at the model.
